/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.28                          *
*        Compiled Jan 30 2015, 16:41:06                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "main.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0    (GUI_ID_USER + 0x00)
#define ID_TEXT_0    (GUI_ID_USER + 0x01)
#define ID_TEXT_1    (GUI_ID_USER + 0x02)
#define ID_TEXT_2    (GUI_ID_USER + 0x03)
#define ID_SLIDER_0    (GUI_ID_USER + 0x04)
#define ID_SLIDER_1    (GUI_ID_USER + 0x05)
#define ID_TEXT_3    (GUI_ID_USER + 0x06)
#define ID_TEXT_4    (GUI_ID_USER + 0x07)
#define ID_TEXT_5    (GUI_ID_USER + 0x08)
#define ID_TEXT_6    (GUI_ID_USER + 0x09)
#define ID_TEXT_7    (GUI_ID_USER + 0x0A)
#define ID_TEXT_8    (GUI_ID_USER + 0x0B)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 480, 272, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Title", ID_TEXT_0, 179, 10, 122, 24, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "STEER_1", ID_TEXT_1, 5, 55, 74, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "STEER_2", ID_TEXT_2, 5, 135, 74, 20, 0, 0x0, 0 },
  { SLIDER_CreateIndirect, "CTRL_1", ID_SLIDER_0, 10, 80, 460, 30, 0, 0x0, 0 },
  { SLIDER_CreateIndirect, "CTRL_2", ID_SLIDER_1, 10, 160, 460, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "SCALE_1_0", ID_TEXT_3, 12, 110, 8, 12, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "SCALE_1_90", ID_TEXT_4, 233, 110, 14, 12, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "SCALE_1_180", ID_TEXT_5, 460, 110, 20, 12, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "SCALE_2_0", ID_TEXT_6, 12, 190, 8, 12, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "SCALE_2_90", ID_TEXT_7, 233, 190, 14, 12, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "SCALE_2_180", ID_TEXT_8, 460, 190, 20, 12, 0, 0x64, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Window'
    //
    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, 0x00C0C0C0);
    //
    // Initialization of 'Title'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetText(hItem, "Steer Driver");
    TEXT_SetFont(hItem, GUI_FONT_24B_ASCII);
    //
    // Initialization of 'STEER_1'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetFont(hItem, GUI_FONT_COMIC18B_ASCII);
    //
    // Initialization of 'STEER_2'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetFont(hItem, GUI_FONT_COMIC18B_ASCII);
    //
    // Initialization of 'SCALE_1_0'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetText(hItem, "0");
    //
    // Initialization of 'SCALE_1_90'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetText(hItem, "90");
    //
    // Initialization of 'SCALE_1_180'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
    TEXT_SetText(hItem, "180");
    //
    // Initialization of 'SCALE_2_0'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
    TEXT_SetText(hItem, "0");
    //
    // Initialization of 'SCALE_2_90'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
    TEXT_SetText(hItem, "90");
    //
    // Initialization of 'SCALE_2_180'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
    TEXT_SetText(hItem, "180");
		//
		// Initialization of 'CTRL_1'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_0);
		SLIDER_SetNumTicks(hItem, 46);
		SLIDER_SetRange(hItem, 0, 100);
		//
		// Initialization of 'CTRL_2'
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_1);
		SLIDER_SetNumTicks(hItem, 46);
		SLIDER_SetRange(hItem, 0, 100);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_SLIDER_0: // Notifications sent by 'CTRL_1'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
				TIMx->CCR1 = 500 + 20 * SLIDER_GetValue(pMsg->hWinSrc);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_SLIDER_1: // Notifications sent by 'CTRL_2'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
				TIMy->CCR1 = 500 + 20 * SLIDER_GetValue(pMsg->hWinSrc);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateWindow(void);
WM_HWIN CreateWindow(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       MainTask
*/
void MainTask(void) {
	CreateWindow();
	while(1) {
		GUI_Delay(10);
	}
}
// USER END

/*************************** End of file ****************************/
