/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.28                          *
*        Compiled Jan 30 2015, 16:41:06                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "desktop_1.c"
#include "uSD_ico.c"
#include "iTunes_ico.c"
#include "iTunes2_ico.c"
#include "picViewer_ico.c"
#include "camera_ico.c"
#include "calculator_ico.c"
#include "IoT_ico.c"
#include "cpu_utils.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x00)
#define ID_IMAGE_0 (GUI_ID_USER + 0x01)
#define ID_ICONVIEW_0 (GUI_ID_USER + 0x02)
#define ID_PROGBAR_0 (GUI_ID_USER + 0x04)
#define ID_TEXT_0 (GUI_ID_USER + 0x05)

// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 480, 272, 0, 0x0, 0 },
  { IMAGE_CreateIndirect, "Image", ID_IMAGE_0, 0, 0, 480, 272, 0, 0, 0 },
//  { ICONVIEW_CreateIndirect, "Iconview", ID_ICONVIEW_0, 0, 0, 480, 200, 0, 0x0, 0 },
  { PROGBAR_CreateIndirect, "Progbar", ID_PROGBAR_0, 350, 250, 120, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "CPULoad:", ID_TEXT_0, 258, 250, 100, 20, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END
extern WM_HWIN CreateCalculator(void);
extern WM_HWIN CreateFileTreeview(void);
/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN      hItem;
  int          NCode;
  int          Id;

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Image'
    //
	hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_0);
	IMAGE_SetBitmap(hItem, &bmdesktop_1);
	//
    // Initialization of 'CPUUsage:'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetFont(hItem, GUI_FONT_20B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_ICONVIEW_0: // Notifications sent by 'Iconview'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
	  if(ICONVIEW_GetSel(WM_GetDialogItem(pMsg->hWin, ID_ICONVIEW_0)) == 1)
		CreateCalculator();
	  if(ICONVIEW_GetSel(WM_GetDialogItem(pMsg->hWin, ID_ICONVIEW_0)) == 0)
		CreateFileTreeview();
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SCROLL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

// USER START (Optionally insert additional public code)
/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       MainTask
*/
void MainTask(void)
{
	WM_HWIN hWin;
	ICONVIEW_Handle hIcon;

	hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
	hIcon = ICONVIEW_CreateEx(0, 0, 480, 230,
			hWin, WM_CF_SHOW | WM_CF_HASTRANS, 
			ICONVIEW_CF_AUTOSCROLLBAR_V, ID_ICONVIEW_0, 120, 110);
	ICONVIEW_AddBitmapItem(hIcon, &bmuSD_s, "uSD Reader");
//	ICONVIEW_AddBitmapItem(hIcon, &bmcamera_s, "Camera");
//	ICONVIEW_AddBitmapItem(hIcon, &bmiTunes2_s, "Music Player");
//	ICONVIEW_AddBitmapItem(hIcon, &bmpicViewer_s, "Image Viewer");
	ICONVIEW_AddBitmapItem(hIcon, &bmcalculator_s, "Calculator");
	ICONVIEW_AddBitmapItem(hIcon, &bmIoT_s, "IoT Apps");

//	ICONVIEW_AddBitmapItem(hIcon, &bmuSD_s, "uSD Reader");
	ICONVIEW_AddBitmapItem(hIcon, &bmcamera_s, "Camera");
	ICONVIEW_AddBitmapItem(hIcon, &bmiTunes2_s, "Music Player");
//	ICONVIEW_AddBitmapItem(hIcon, &bmpicViewer_s, "Image Viewer");

	ICONVIEW_SetBkColor(hIcon, ICONVIEW_CI_SEL, GUI_BLUE | 0xC0000000);
	ICONVIEW_SetFont(hIcon, &GUI_Font13B_ASCII);
	ICONVIEW_SetIconAlign(hIcon, ICONVIEW_IA_TOP | ICONVIEW_IA_HCENTER);
	while(1)
	{
		GUI_Delay(900);
		GUI_Exec();
		PROGBAR_SetValue(WM_GetDialogItem(hWin, ID_PROGBAR_0), osGetCPUUsage());
	}
}
// USER END

/*************************** End of file ****************************/
